package com.mycompany.unbound.vista;

import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import java.awt.event.MouseListener;

/**
 *
 * @author Admin
 */
public class GUILaberinto extends javax.swing.JFrame {

    /**
     * Creates new form GUILaberinto
     */
    public GUILaberinto() {
        initComponents();

    }

    public PanelLaberinto getPanelLaberinto() {
        return this.panelLaberinto;
    }

    public void escuchar(ActionListener controlador) {
        btnMenu.addActionListener(controlador);
    }

    public void escucharMouse(MouseListener controlador) {
        this.addMouseListener(controlador);
    }
//se crea y despus se pasa por parametro

    public void escucharKey(KeyListener controlador) {
        this.addKeyListener(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLaberinto = new com.mycompany.unbound.vista.PanelLaberinto();
        btnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLaberinto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visual_menu.png"))); // NOI18N
        btnMenu.setActionCommand("showInGameMenu");
        btnMenu.setBorder(null);
        btnMenu.setBorderPainted(false);
        btnMenu.setContentAreaFilled(false);
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        panelLaberinto.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(721, 720, -1, -1));

        getContentPane().add(panelLaberinto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private com.mycompany.unbound.vista.PanelLaberinto panelLaberinto;
    // End of variables declaration//GEN-END:variables
}
